[build]
  base = "."
  command = "cd apps/web && pnpm build"
  publish = "apps/web/dist"

[build.environment]
  NODE_ENV = "staging"
  VITE_ENVIRONMENT = "staging"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions" 